#!/usr/bin/env python
"""E6 — can Haiku narrate the stops of a road? (path-interface feasibility)

Walk the unrelated fig-05 pair (coding-interview video -> instagram heatmap),
pull the top-3 real notes at three stops, and have Haiku merge them into a
description of the "place", weighted by retrieval cosine. This is the
smallest end-to-end slice of the path interface: slerp -> retrieve -> merge.

Reads the fresh capture in docs/assets/17-corpus-growth/ plus note text from
Chroma (read-only). Output: blend-demo.md next to the figures, one section
per stop with the evidence (retrieved notes + weights) above the narration,
so the merge can be judged against its inputs.

    uv run python scripts/path_blend_demo.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).resolve().parent))
from growth_experiments import PAIR_A, PAIR_B_UNRELATED, _load, slerp

OUTDIR = Path(__file__).resolve().parents[1] / "docs" / "assets" / "17-corpus-growth"
STOPS = (0.25, 0.5, 0.75)
TOP_K = 3

SYSTEM = """You narrate stops along a walk between two notes in a personal
knowledge vault. The walk blends the two endpoint topics; at each stop you get
the blend ratio and the real saved notes nearest to that point, each with a
weight. Describe the place: the single idea living at this blend, grounded
ONLY in the provided notes, leaning on each in proportion to its weight.
2-3 sentences. No preamble, no meta-commentary about walks or vectors."""


class StopBlend(BaseModel):
    place: str


def note_texts() -> dict[str, str]:
    """name -> text, keyed exactly the way harvest() keys names."""
    from ytk import store

    texts: dict[str, str] = {}
    vids = store._videos_collection().get(include=["documents", "metadatas"])
    for doc, meta in zip(vids["documents"], vids["metadatas"]):
        texts[str(meta.get("title", meta.get("video_id", "")))[:80]] = doc or ""
    mem = store._memories_collection().get(include=["documents", "metadatas"])
    for doc, meta in zip(mem["documents"], mem["metadatas"]):
        path = str(meta.get("source_path", ""))
        if path:
            texts[Path(path).stem[:80]] = doc or ""
    return texts


def main() -> None:
    from ytk.sdk import structured

    X, meta = _load("fresh")
    names = meta["names"]
    texts = note_texts()
    i, j = names.index(PAIR_A), names.index(PAIR_B_UNRELATED)

    lines = [
        "# Blend demo — narrating the road from a coding-interview video to an instagram heatmap",
        "",
        f"Endpoints: **{names[i].strip()}** (A) and **{names[j].strip()}** (B).",
        "At each stop: top-3 notes by cosine to the slerp point (endpoints excluded),",
        "weights are cosines normalised to sum 1, narration by claude-haiku-4-5 via",
        "`ytk.sdk.structured`. Generated by `scripts/path_blend_demo.py`.",
        "",
    ]
    for t in STOPS:
        v = slerp(X[i], X[j], t)
        s = X @ v
        s[[i, j]] = -1
        top = np.argsort(-s)[:TOP_K]
        w = s[top] / s[top].sum()

        evidence = []
        for k, wk in zip(top, w):
            body = texts.get(names[k], "").strip().replace("\n", " ")[:450]
            evidence.append(f"[weight {wk:.2f}] {names[k].strip()}: {body}")
        user = (
            f"Endpoint A: {names[i].strip()}\nEndpoint B: {names[j].strip()}\n"
            f"Blend ratio: {1 - t:.2f} A / {t:.2f} B\n\nNearest notes:\n" + "\n\n".join(evidence)
        )
        blend = structured(SYSTEM, user, StopBlend)

        lines.append(f"## Stop t = {t:.2f}  ({1 - t:.0%} A / {t:.0%} B)")
        lines.append("")
        for k, wk in zip(top, w):
            lines.append(f"- `{s[k]:+.3f}` (weight {wk:.2f}) — {names[k].strip()}")
        lines.append("")
        lines.append(f"> {blend.place.strip()}")
        lines.append("")
        print(f"t={t:.2f}  {blend.place.strip()}\n")

    (OUTDIR / "blend-demo.md").write_text("\n".join(lines))
    print(f"-> {OUTDIR / 'blend-demo.md'}")


if __name__ == "__main__":
    main()
