/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecsRouteImport } from './routes/recs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrbRouteImport } from './routes/orb'
import { Route as MapRouteImport } from './routes/map'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSectionRouteImport } from './routes/docs.$section'

const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecsRoute = RecsRouteImport.update({
  id: '/recs',
  path: '/recs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbRoute = OrbRouteImport.update({
  id: '/orb',
  path: '/orb',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSectionRoute = DocsSectionRouteImport.update({
  id: '/docs/$section',
  path: '/docs/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/galaxy': typeof GalaxyRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/orb': typeof OrbRoute
  '/profile': typeof ProfileRoute
  '/recs': typeof RecsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/transit': typeof TransitRoute
  '/docs/$section': typeof DocsSectionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/galaxy': typeof GalaxyRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/orb': typeof OrbRoute
  '/profile': typeof ProfileRoute
  '/recs': typeof RecsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/transit': typeof TransitRoute
  '/docs/$section': typeof DocsSectionRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/galaxy': typeof GalaxyRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/orb': typeof OrbRoute
  '/profile': typeof ProfileRoute
  '/recs': typeof RecsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/transit': typeof TransitRoute
  '/docs/$section': typeof DocsSectionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/galaxy'
    | '/garden'
    | '/growth'
    | '/inbox'
    | '/library'
    | '/map'
    | '/orb'
    | '/profile'
    | '/recs'
    | '/settings'
    | '/tags'
    | '/transit'
    | '/docs/$section'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/galaxy'
    | '/garden'
    | '/growth'
    | '/inbox'
    | '/library'
    | '/map'
    | '/orb'
    | '/profile'
    | '/recs'
    | '/settings'
    | '/tags'
    | '/transit'
    | '/docs/$section'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/galaxy'
    | '/garden'
    | '/growth'
    | '/inbox'
    | '/library'
    | '/map'
    | '/orb'
    | '/profile'
    | '/recs'
    | '/settings'
    | '/tags'
    | '/transit'
    | '/docs/$section'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  GalaxyRoute: typeof GalaxyRoute
  GardenRoute: typeof GardenRoute
  GrowthRoute: typeof GrowthRoute
  InboxRoute: typeof InboxRoute
  LibraryRoute: typeof LibraryRoute
  MapRoute: typeof MapRoute
  OrbRoute: typeof OrbRoute
  ProfileRoute: typeof ProfileRoute
  RecsRoute: typeof RecsRoute
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
  TransitRoute: typeof TransitRoute
  DocsSectionRoute: typeof DocsSectionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recs': {
      id: '/recs'
      path: '/recs'
      fullPath: '/recs'
      preLoaderRoute: typeof RecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orb': {
      id: '/orb'
      path: '/orb'
      fullPath: '/orb'
      preLoaderRoute: typeof OrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$section': {
      id: '/docs/$section'
      path: '/docs/$section'
      fullPath: '/docs/$section'
      preLoaderRoute: typeof DocsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  GalaxyRoute: GalaxyRoute,
  GardenRoute: GardenRoute,
  GrowthRoute: GrowthRoute,
  InboxRoute: InboxRoute,
  LibraryRoute: LibraryRoute,
  MapRoute: MapRoute,
  OrbRoute: OrbRoute,
  ProfileRoute: ProfileRoute,
  RecsRoute: RecsRoute,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
  TransitRoute: TransitRoute,
  DocsSectionRoute: DocsSectionRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
