catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:vitest@^4.0.0
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
