import { defineConfig } from "vite-plus";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// The SPA is served by FastAPI at the root; built asset URLs live under
// /assets to match the backend mount. The dev server proxies backend
// routes to the hub on :6969.
export default defineConfig({
  base: "/",
  resolve: {
    alias: { "@": new URL("./src", import.meta.url).pathname },
  },
  server: {
    port: 5173,
    proxy: {
      "/api": "http://127.0.0.1:6969",
      "/vault-media": "http://127.0.0.1:6969",
      "/favicon.svg": "http://127.0.0.1:6969",
    },
  },
  // dist/ is committed build output shipped inside the Python wheel, and
  // routeTree.gen.ts is generated by the TanStack router plugin. Formatting
  // either one rewrites a file nothing authors by hand — and reformatting the
  // minified bundle would ship a beautified dist.
  fmt: {
    ignorePatterns: ["dist/**", "src/routeTree.gen.ts"],
  },
  lint: {
    // Generated output is checked by the build, not source-oriented lint rules.
    ignorePatterns: ["dist/**", "src/routeTree.gen.ts"],
    plugins: ["react", "typescript", "oxc"],
    rules: {
      "react/rules-of-hooks": "error",
      // Type-aware correctness rules are blocking for hand-written source.
      "typescript/unbound-method": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-implied-eval": "error",
      "typescript/restrict-template-expressions": "error",
      "eslint/no-unused-expressions": "error",
      // TanStack route modules must export Route alongside their component.
      "react/only-export-components": "off",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  plugins: [
    tailwindcss(),
    tanstackRouter({
      target: "react",
      routeFileIgnorePattern: String.raw`\.test\.tsx$`,
    }),
    react(),
  ],
});
